channels_not_to_consider = [
    #traffic
    '511NY', '511NYC', 'TotalTrafficNYC', '511nyNJ', '511NYMidHudson',
    'Reported_NYC', '511ny456', '511nyAlbany', '511nyACE', '511ny123', 
    '511nyBDFV', '511nyWNY', '511nyRochester',
    '511nyLongIsland', 'AllKindsWeather', 
    '511ny7',
    #jobs
    'tmj_nyc_jobs', 'tmj_nyc_adv', 'CalvaryHospJobs',
   'tmj_RAM_cstsrv', 'tmj_nyc_mgmt', 'tmj_roc_cler',
   'tmj_NAS_edu', 'tmj_nyc_it', 'tmj_NYC_schn', 'tmj_NJN_cstsrv',
   'tmj_nwk_retail', 'tmj_nyc_nursing', 'tmj_nyc_sales', 'tmj_nyc_cler',
   'USSJobs', 'tmj_nwk_sales', 'tmj_nyc_legal', 'tmj_nwk_eng',
   'tmj_nyc_retail', 'tmj_nyc_transp', 'WGPNursingJobs', 'tmj_nwk_socsci',
   'tmj_NYC_adm', 'nwkmeddevice', 'tmj_nyc_edu', 'tmj_nwk_secure',
   'nwknursing',
   'tmj_nyc_finance', 'tmj_NYC_secure', 'tmj_nyc_acct', 'tmj_nwk_cler',
   'tmj_nyc_banking', 'tmj_ny_hrta', 'tmj_nwk_mgmt', 'tmj_nwk_auto',
   'tmj_nyc_cstsrv', 'tmj_nyc_health', 'nwkhealth', 'tmj_nwk_cstsrv',
   'tmj_nyc_manuf', 'tmj_cte_nursing', 'tmj_nyc_eng', 'tmj_nyc_itpm1',
   'tmj_nyc_hr', 'tmj_NY_sales', 'CVSHealthJobs', 'tmj_NAS_mgmt',
   'CompassJobBoard', 'tmj_nyc_hrta', 'tmj_NAS_nursing', 'BostonMarketJob',
   'tmj_nyc_labor', 'MetsAvenue', 'tmj_nwk_schn', 'tmj_RAM_nursing',
   'tmj_nwk_acct', 'tmj_nwk_jobs', 'tmj_nyc_art', 'tmj_nwk_labor',
   'tmj_roc_eng', 'tmj_NAS_transp', 'CA_ROC_Jobs2', 'tmj_nyc_cosmo',
   'tmj_RAM_edu', 'tmj_NAS_health', 'tmj_nwk_facmgmt', 'tmj_NAS_facmgmt',
   'GodivaJobs', 'tmj_RAM_acct', 'tmj_roc_health', 'tmj_nyc_itdb',
   'tmj_nwk_transp', 'tmj_nwk_edu', 'tmj_RAM_retail', 'tmj_RAM_mgmt',
   'tmj_NAS_socsci', 'tmj_nwk_prod', 'tmj_nyc_realest', 'tmj_NJ_facmgmt', 'tmj_njn_retail',
   'tmj_roc_nursing', 'tmj_nwk_finance', 'Fly_Sistah', 'tmj_NYC_skltrd',
   'tmj_nya_nursing', 'tmj_nwk_web', 'tmj_roc_cstsrv', 'tmj_nys_jobs',
   'tmj_njc_hrta', 'tmj_NAS_retail', 'tmj_roc_hrta',
   'ChurchCathy', 'tmj_NAS_secure', 'tmj_RAM_art', 'tmj_NAS_labor',
   'tmj_NAS_physici', 'tmj_nwk_skltrd', 'tmj_roc_sales', 'tmj_nwk_purch',
   'tmj_NYS_NURSING', 'tmj_nwk_physici', 'tmj_njn_hrta', 'Mezikenyc',
   'JCI_Jobs', 'tmj_NAS_acct', 'tmj_NYC_gensci', 'tmj_nya_eng',
   'tmj_nwk_nonprft', 'tmj_roc_manuf', 'nwkitsupport', 'tmj_NY_LABOR',
   'tmj_ny_mgmt', 'tmj_njn_health',
   'tmj_nj_hrta', 'tmj_NAS_cstsrv', 'tmj_nwk_it', 'tmj_nya_transp',
   'tmj_ct_nursing', 'tmj_NJ_sales', 'tmj_nya_acct',
   'nwkmanuf', 'tmj_nys_cstsrv', 'tmj_njn_nursing',
   'tmj_njn_mgmt', 'cbwaszak', 'tmj_NAS_cler', 'tmj_RAM_auto',
   'tmj_nwk_art'
   'WWEWomenMatter',
   #photos
   'ThomGambino', 'Xsanthemum', 'francesco212', 'Empressjurnee',
   'andrerivera801', 'janice830', 'Ingridebap', 'StevieSoFetch_',
   'EstebanDaHost', 'graceyhanderson', 'bccdny', 'brian_wood_'
       ]